version: "3.8"

services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: mydb
    depends_on:
      - db
    networks:
      - app-net
    restart: on-failure

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-net
    restart: on-failure

volumes:
  db-data:
    external: true

networks:
  app-net:
    external: true
